# Generated by Django 4.2 on 2024-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livero', '0007_remove_readings_liver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='chironic_dieases',
            field=models.ManyToManyField(blank=True, related_name='reading_chi', to='livero.chronicdiseases'),
        ),
        migrations.AlterField(
            model_name='readings',
            name='fbi_result',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='name',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
